#!/usr/bin/env node
var request = require('request'),
    requestedUrl = process.argv[2];
if (!requestedUrl) {
    console.log('Provide a working url to check');
    process.exit();
} else {
    console.time('Request for ' + requestedUrl + ' took');
    var req = request(requestedUrl, function (error, response, body) {
        console.timeEnd('Request for ' + requestedUrl + ' took');
        if (!error && response.statusCode === 200) {
            console.log('Page loaded successfully!');
        } else if (!error) {
            console.log('Failure with statuscode: ' + response.statusCode);
        } else {
            console.log('Failed to load the page with url ' + requestedUrl);
            console.log(error);
        }
    });
}
